mysql:
  ports:
  - ${MYSQL_DBPORT}:3306/tcp
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: mysql:latest
  volumes:
  - /www/mysql_test:/var/lib/mysql
  stdin_open: true
mysql-backup:
  environment:
    MYSQL_HOST: mysql
    MYSQL_PORT: '3306'
    MYSQL_USER: root
    MYSQL_PASS: ${MYSQL_ROOT_PASSWORD}
    CRON_TIME: '*/5 * * * *'
    MAX_BACKUPS: '3'
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: tutum/mysql-backup
  links:
  - mysql:mysql
  volumes:
  - /www/mysql_backup:/backup
  stdin_open: true
